### ISSUE TITLE
TL for Extension Install/Update notice

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/kc3-translations#297]
### Terminologies Added
- `InstalledTitle` - "_KC3改 ready for service!_"
- `InstallText` - "_Thank you for installing KC3改! We hope that these tools can help you play KanColle and make it a better experience! Do not hesitate to approach us if you need help. Check the about page to know where we can be reached._"
- `UpdatedTitle` - "_KC3改 has been updated!_"
- `UpdateText` - "_If you are currently playing KanColle, some features in the viewer might be bugged. Please close the game tab and restart the game. If you are in the middle of a sortie, please finish it first, but know what some features such as info and prediction might not work as expected before restarting._"
### Reference

https://github.com/KC3Kai/kc3-translations/commit/5de735756496ffb4ed5e7370b810c93b243c2ca1
### Checklist

@KC3Kai/translators, tick on your language once you're done and you have the updates in `master` branch.
- [x] `en` English
- [ ] `de` Deutsch
- [ ] `nl` Dutch
- [ ] `es` Español
- [ ] `fr` Français
- [x] `id` Indonesian
- [ ] `it` Italiano
- [x] `jp` 日本語
- [ ] `kr` 한국어
- [ ] `pt` Português
- [x] `ru` Русский
- [x] `scn` 简体中文
- [x] `tcn` 繁體中文
- [x] `th` ภาษาไทย
- [ ] `vi` Tiếng Việt

**Comment by sinsinpub** [comment]
@dragonjet A question: view button texts in `update.html` are not supported for l10n yet?

Borrow here to notify:

### Terminologies Removed
* `PanelEscortChuuha`: "Escort Flagship"

### Reference
This term has been removed for this [PR](https://github.com/KC3Kai/KC3Kai/pull/1511), it's reserved for compatibility of old TL version before webstore releasing. And it's okay to clean it up now.

https://github.com/KC3Kai/kc3-translations/commit/8a50d297fda33f39155f0c41d276c96420d6a6ca

### Checklist
@KC3Kai/translators, tick on your language once you're done and you have the updates in `master` branch.
* [x] `en` English
* [ ] `de` Deutsch
* [ ] `nl` Dutch
* [ ] `es` Español
* [ ] `fr` Français
* [ ] `id` Indonesian
* [ ] `it` Italiano
* [x] `jp` 日本語
* [ ] `kr` 한국어
* [ ] `pt` Português
* [ ] `ru` Русский
* [ ] `scn` 简体中文
* [ ] `tcn` 繁體中文
* [ ] `th` ภาษาไทย
* [ ] `vi` Tiếng Việt

**Comment by dragonjet** [comment]
you're right I forgot about the button :sweat_smile:
