### ISSUE TITLE
Is there any corrections still ongoing on kc3 kai

### ISSUE THREAD

**Issue by Tamachan12** [KC3Kai/kc3-translations#303]
### Terminologies Added
- `term_name` - english_base 
- `term_name` - english_base 
- `term_name` - english_base 
### Checklist

@KC3Kai/translators, tick on your language once you're done and you have the updates in `master` branch.
- [ ] `en` English
- [ ] `de` Deutsch
- [ ] `nl` Dutch
- [ ] `es` Español
- [ ] `fr` Français
- [ ] `id` Indonesian
- [ ] `it` Italiano
- [ ] `jp` 日本語
- [ ] `kr` 한국어
- [ ] `pt` Português
- [ ] `ru` Русский
- [ ] `scn` 简体中文
- [ ] `tcn` 繁體中文
- [ ] `th` ภาษาไทย
- [ ] `vi` Tiếng Việt

**Comment by dragonjet** [comment]
@Tamachan12 ?
