### ISSUE TITLE
[ID] Regarding Rank Translations

### ISSUE THREAD

**Issue by ethrundr** [KC3Kai/kc3-translations#310]
@freezebear @KC3Kai/translators 

Since I just noticed that there is TL error on the Rank for ID language, I think it'll be a good opportunity to check other languages as well for standardization.

As we know, in the english translations:
- 少将 translated into "Rear-Admiral", a two-starred Officer.
- 中将 translated into "Vice-Admiral", a three-starred Officer.
- 大将 translated into "Admiral", a four-starred Officer.
- 元帥 translated into "Marshal Admiral", a five-starred Officer or other honorary title above the 'Admiral'.

In ID TL, there is error for the 少将, which then translated into "Laksamana Pertama", which is one-starred Officer here. It should be "Laksamana Muda", the title for two-starred Officer.

For other language, please make sure that your translation refers to the correct star's titles.

**Comment by freezebear** [comment]
@ethrundr everything looks fine for me, but..
is it ok to make a confirmation again at the group ? 
(i guess it's ok)

**Comment by ethrundr** [comment]
Oh, forgot to mention one thing:

If referring to the english translation on the wikia, please take note that the One-starred Officer rank (Commodore) is **skipped**.

After the two-starred rank "Rear-Admiral", the next lower level in the KC's rank directly jumped into "Captain", which is the highest mid-ranked Officer.

**Comment by freezebear** [comment]
hmm.. k~
will fix soon..
