### ISSUE TITLE
EN New Terms for 30.10.1

### ISSUE THREAD

**Issue by dragonjet** [KC3Kai/kc3-translations#312]
### Terminologies Added
- `GameAPIPlayFlashNoticeTitle`
- `GameAPIPlayFlashNoticeDesc`
- `GameAPIPlayFlashNoticeStep1`
- `GameAPIPlayFlashNoticeStep2`
- `GameAPIPlayFlashNoticeStep3`
- `GameAPIPlayFlashNoticeStep4`
- `APIErrorNoticeTitle`
- `APIErrorNoticeMessage`
- `Bomb201Title`
- `Bomb201Message` (**correction** _You have received an error 201 from the game API. You could be still logged in on another game client, or this may have something to do with macro-detection. You may ignore this notice but please play in moderation._)
- `NewVerViewChangelogGithub`
- `NewVerViewWikiGithub`
- `SettingsStrategyRoom`
- ~~`SettingsLevellingDifference`~~(**unused, you can remove this**)
- `SettingsStrategyTheme`
- `SettingsAPIRecorder`
- `MenuScheduledSoon` ("_Soon..._" to "_unscheduled_")
### Checklist

@KC3Kai/translators, tick on your language once you're done and you have the updates in `master` branch.
- [x] `en` English
- [ ] `de` Deutsch
- [ ] `nl` Dutch
- [ ] `es` Español
- [ ] `fr` Français
- [x] `id` Indonesian
- [ ] `it` Italiano
- [x] `jp` 日本語
- [ ] `kr` 한국어
- [ ] `pt` Português
- [x] `ru` Русский
- [x] `scn` 简体中文
- [ ] `tcn` 繁體中文
- [x] `th` ภาษาไทย
- [ ] `vi` Tiếng Việt

**Comment by Javran** [comment]
just to point out that `SettingsLevellingDifference` is removed previously by https://github.com/KC3Kai/KC3Kai/pull/1470

**Comment by Javran** [comment]
also note that error 201 can also be a result of logining the game using other clients (e.g. android client), which I feel is a more common case, translators can also mention that accordingly in the error message.

**Comment by dragonjet** [comment]
ah I'll change `en` to:
_You have received an error 201 from the game API. You could be still logged in on another game client, or this may have something to do with macro-detection. You may ignore this notice but please play in moderation._

and will remove `SettingsLevellingDifference` :+1:
