### ISSUE TITLE
About slotitem equiptype translations

### ISSUE THREAD

**Issue by sinsinpub** [KC3Kai/kc3-translations#348]
### Terminologies Added
5 arrays in `equiptype.json`.
5 categories stand for: major category, minor category, master category, icon ID, aircraft image ID, which 'master category' has official Japanese texts inside master data `slotitem_equiptype` object, and icon & aircraft IDs are not needed to be translated indeed.

Sample texts could be found in `EN` / `JP` / `SCN` folder, low priority to translate 3 categories as not used much for now. currently only used in Strategory Room Equipment Library, could test them there. May be used in future for the category names of yet another equipment list page.

btw, some IDs are not used (skipped) by KC official devs, they are marked as `?` for now as placeholders, donot remove them from array.

### Checklist
@KC3Kai/translators, tick on your language once you're done and you have the updates in `master` branch.
* [x] `en` English
* [ ] `de` Deutsch
* [ ] `nl` Dutch
* [ ] `es` Español
* [ ] `fr` Français
* [ ] `id` Indonesian
* [ ] `it` Italiano
* [x] `jp` 日本語
* [ ] `kr` 한국어
* [ ] `pt` Português
* [ ] `ru` Русский
* [x] `scn` 简体中文
* [x] `tcn` 繁體中文
* [ ] `th` ภาษาไทย
* [ ] `vi` Tiếng Việt
* [ ] `ua` Українська

**Comment by sinsinpub** [comment]
The names of major category not exists in game, researching is required for proper EN names. Btw, JP ones are just copied from [EO74 repo].(https://github.com/andanteyk/ElectronicObserver/blob/develop/ElectronicObserver/Other/Information/apilist.txt?ts=4#L114)
Minor category is used to organize Picture Book in game, also no names found. The EN ones are also from EO74 repo.
Master category is also used to display at Picture Book in game, official names found in master data. Proper EN translations is needed.

**Comment by nonsensed** [comment]
I changed exisiting translations. If this is a problem, let me know. They are now synced with translations from

http://kancolle.wikia.com/wiki/Equipment

Some lines are very long. I think this is a problem if this gets used for more things. I can shorten them if needed. Should be no problem.

**Comment by sinsinpub** [comment]
@nonsensed 👍 np for now.
![image](https://cloud.githubusercontent.com/assets/160240/21542803/9654f446-cdfb-11e6-82f6-cd67bb4fa8e7.png)
so long as this, some abbreviations may be needed in future... lul

**Comment by Javran** [comment]
just spotted something weird: 
![2016-12-30_035002_3840x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/21562080/3b08b3be-ce43-11e6-8ddb-42920cf16ed1.jpg)

obviously damecons are not flying boats.. maybe there's an offset?

**Comment by sinsinpub** [comment]
@Javran u have not synced json yet? there are 3 ids skipped...
