### ISSUE TITLE
Official suspension of KR term support

### ISSUE THREAD

**Issue by rephira** [KC3Kai/kc3-translations#408]
Hi all,

I am here to officially state that I will be suspending support of KR terms update altogether.
I have left the game at the time of Winter Event 2017, and foresee that I will not be returning to it any time soon, if ever.
With that states, I am willing to pass the rein of the core work to another capable translator to spearhead the project.
I will continue to update new quote lines that come in for new girls.
However, KR will NOT get any support regarding seasonal lines, as I am extremely against the way that the seasonal lines are being implemented for EN right now. (Purely technical perspective. Kudos for nonsensed for having it working despite such manual labor)

**Comment by ethrundr** [comment]
Good work there, @rephira!
Thanks for all your contributions so far :)
