### ISSUE TITLE
about the quotes

### ISSUE THREAD

**Issue by abs15986** [KC3Kai/kc3-translations#628]
关于kc3改自动调用季节性语音字幕的系统，我有一些想法与建议：

我发现现有的系统存在两个问题：
    1、官方有时会将旧季节语音更换语音位置重复进行使用，（比如2@spring条目下一年可能就会变为3@spring，这时调用就会失效）需要编辑各语言的quotes文件。
    2、以时长属性进行匹配语音调目，有唯一性不高的缺点。若按照我的解决思路，需要以唯一性更高的属性进行匹配。

解决思路：
    减少语音字幕调用分类，直接按舰船ID作为一级目录，通过语音属性索引来匹配语音字幕条目，因为一条语音总是对应一条字幕的，这样以后即使存在语音编号移位，也会自动匹配到正确的字幕。不再需要任何调整。
    唯一性不高的问题，我能想到的是以语音文件时长及大小两者作为合并条件进行匹配，如果你们能够找到更好的唯一属性就更好了。

   同时，现有的各语言的quotes文件存在部分历史条目混乱的问题，若整合调整完毕，也可以对各语言的字幕数据库整理归档提供帮助

@sinsinpub

**Comment by sinsinpub** [comment]
第1点针对Poke(1/2/3)已经有特殊处理了，你没发现么。。。？例如，当应该去匹配`3@spring`时，如果没有在quotes文件中找到该项，会再顺序尝试查找`2@spring`和`4@spring`，如果找到会直接用来显示的。

你的解决思路我没看懂，“语音属性索引”具体指的是什么，哪个或哪些属性呢？
需要解释的是现在用的语音序号不是我们发明的。在早期游戏还没把语音文件名“加密”处理之前，语音文件就是按序号来命名的，例如母港戳一下（`Poke(1)`）的访问的文件名就是`2.mp3`。所以语音序号它就是语音和文字内容匹配的惟一属性。后来游戏实现了季节语音，但开发者是用不同内容的语音文件直接覆盖替换到了对应的语音序号上，才有了现在的麻烦事。

第2点结果是你和我们都并没有找到“更高的属性”。语音(mp3)文件的时长(duration)是不存在于HTTP响应中的，无法直接”提取“到。作为这种媒体文件的内部元属性，如果要用JavaScript获取，需要创建HTML5的`Audio`对象来解析下载到的mp3流。但这个行为不便于在“旁听”游戏Flash请求mp3文件时进行。如果我们自己的程序“另外发起一个HTTP请求”来下载、解析，虽然可能得到duration值，但这个方案由于有可能大量向游戏服务端发起额外的HTTP请求，有被运营方发现导致被ban的风险，所以没被通过。

顺便，这样的issue应该开到主repo去，而不是在这边讨论。

**Comment by sinsinpub** [comment]
现有实现并不是用时长(`duration`)，而就是文件大小(HTTP响应头中的`content-size`)，当然还结合了文件名(就在URL中)本身。

语音序号（标志语音用途、事件类型，从文件名逆推得到）并不会变更，变更的是服务器实际返回的语音内容而已。。。 😸 
其实如果说要抛弃语音序号重新设计的话，有个“唯一性最高”的东西可以用，那就是文件内容的hash值。我们知道只要hash算法选择得当，不同内容的文件不存在与之相同的hash值。如果在运行时计算mp3文件内容的hash值来与台词内容匹配，那自然不用管内容新旧或是季节。
不过可以预见的缺点也很显然：
 1. 我们维护会更难，一来要将所有历史上实装过的mp3原文件找到，为它们重新计算hash值，并得到很不直观的hash与台词配对的quotes.json文件；二来新的mp3文件如果没有台词内容变化，只是mp3被小修改了一下（例如重新调了音），我们也得为这个不同的hash值绑定与之前相同内容的台词。自然的，旧的hash值还需不需要保留也成了疑问。
 2. 运行时hash计算可能有效率问题。不但需要读取HTTP响应Header，还需要读取全部的Payload。即使我们选择JS计算不那么慢的老旧hash算法（例如md5、sha1），由于mp3文件从十几KB到几MB不等，可能都需要实现hash值缓存功能以减少重复计算。自然“占用系统资源”是会增加。

比起思路的技术实现难度，我个人觉得人工维护成本（重构quotes等JSON文件）可能困难更多些。需要咨询一直用编写脚本维护着它们的 @fourinone41 是否可行。

ps.如果不能用英语的话还是就在这里讨论吧，不用复制了。
