### ISSUE TITLE
Hash for E47B3 and E47B4 are the same

### ISSUE THREAD

**Issue by sorewachigauyo** [KC3Kai/kc3-translations#694]
@sinsinpub

**Comment by sinsinpub** [comment]
oops? forgot to paste the new... will fix it later
btw, just run `.hashCode()` on name string in sroom console. anyone can fix it
![image](https://user-images.githubusercontent.com/160240/76143712-ac573e80-60b4-11ea-9fac-de19e52c6f74.png)
