### ISSUE TITLE
[KR] Incorrect quest code

### ISSUE THREAD

**Issue by lawvs** [KC3Kai/kc3-translations#708]
The code of the  `348` quest on KR should be `C53`

https://github.com/KC3Kai/kc3-translations/blob/e464c49c8288364d36a19c5ae3b77f6356372eb3/data/kr/quests.json#L2234-L2241

See

https://github.com/KC3Kai/kc3-translations/blob/e464c49c8288364d36a19c5ae3b77f6356372eb3/data/en/quests.json#L2370-L2377

and

https://github.com/KC3Kai/kc3-translations/blob/e464c49c8288364d36a19c5ae3b77f6356372eb3/data/kr/quests.json#L2009-L2016

**Comment by whitekiw** [comment]
I will fix it.
Thank you.
