### ISSUE TITLE
[ALL] Am I only one having trouble w/ Natsugumo Kai?

### ISSUE THREAD

**Issue by Agc0de6** [KC3Kai/kc3-translations#769]
Can we do something about it?
[Summer 雲 Kai]
[image](https://user-images.githubusercontent.com/14156630/186944608-92a511fb-03a4-4fb1-8c6f-f557440363dc.png)

**Comment by sinsinpub** [comment]
add full name translation to ships.json ```
	"夏雲改":"Natsugumo Kai",
```
because `夏` is a seasonal prefix too...

**Comment by Agc0de6** [comment]
closing... for now...
