### ISSUE TITLE
Request permission to use English quote translation

### ISSUE THREAD

**Issue by TrickLin** [KC3Kai/kc3-translations#774]
Dear KC3Kai development team,

I am a maintenance team member for the poi-plugin-subtitle, a subtitle plugin of the KanColle browser poi. Our source of the English translation has not been updated for a while, and we are desperate for an alternative. Could you please permit us to use the English translation used by kc3-translation? It would also be helpful if you could tell us the source of your English translation. If it is from en.kancollewiki.net or other organizations, we will make sure to ask them for permission as well.

Thank you very much!

Sincerely,
TrickLin

**Comment by sinsinpub** [comment]
en quotes are mostly crawled by @fourinone41 from en.kancollewiki.net, some minor local tweaks done by other contributors. i guess it's okay to use as long as not be objected by en.kancollewiki.net?
